### ISSUE TITLE
Address nuget error related to package icon

### ISSUE THREAD

**Issue by adamchester** [kmdlogic/kmd-logic-citizen-documents-client#3]
https://aka.ms/deprecateIconUrl

`
/usr/local/share/dotnet/sdk/3.1.100/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl [/Users/adamchester/repo/kmd/kmd-logic-citizen-documents-client/src/Kmd.Logic.CitizenDocuments.Client/Kmd.Logic.CitizenDocuments.Client.csproj]
`

**Comment by ajaygargdev** [comment]
issue is fixed in PR https://github.com/kmdlogic/kmd-logic-citizen-documents-client/pull/15
