### ISSUE TITLE
Improve the 'first run' experience of the example

### ISSUE THREAD

**Issue by adamchester** [kmdlogic/kmd-logic-citizen-documents-client#4]
The first time you run the sample, you will see a strange error such as this:

![image](https://user-images.githubusercontent.com/570470/72126721-ec51bc00-33b8-11ea-818e-7ee447b90579.png)

It will be better if you have a more well written error message here in this case, so the new developers will not get confused about why it's erroring.

**Comment by DommarajuUmamaheswari** [comment]
this issue is fixed in https://github.com/kmdlogic/kmd-logic-citizen-documents-client/pull/16
